<<<<<<< HEAD
# Generated by Django 4.2.19 on 2025-02-22 09:05

=======
# Generated by Django 5.1.6 on 2025-02-22 07:25

import django.db.models.deletion
from django.conf import settings
>>>>>>> 50e3b7a14c5ef3560469bf2fcb5e6f9eacd752db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0001_initial'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 50e3b7a14c5ef3560469bf2fcb5e6f9eacd752db
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
=======
>>>>>>> 50e3b7a14c5ef3560469bf2fcb5e6f9eacd752db
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('semester', models.IntegerField()),
                ('is_student', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 50e3b7a14c5ef3560469bf2fcb5e6f9eacd752db
            ],
        ),
    ]
