# Generated by Django 5.1.6 on 2025-02-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCreator',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('user_classroom_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_password', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassHubApp.classroomcreator')),
            ],
        ),
    ]
