# Generated by Django 4.2.19 on 2025-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_data',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_data',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher_data',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
