# Generated by Django 5.1.6 on 2025-02-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0003_classroomcreator_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassHubApp.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassHubApp.student')),
            ],
        ),
    ]
