# Generated by Django 5.1.6 on 2025-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0003_classroomcreator_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='classroomcreator',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='classroomcreator',
            name='user_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
