# Generated by Django 4.2.19 on 2025-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
