# Generated by Django 5.1.6 on 2025-02-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0004_classroom_classroom_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='creator',
            new_name='user_id',
        ),
    ]
