# Generated by Django 4.2.19 on 2025-02-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0005_remove_student_department_remove_student_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
