# Generated by Django 4.2.19 on 2025-02-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0006_remove_student_section_remove_student_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
