# Generated by Django 4.2.19 on 2025-02-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0004_attendence'),
        ('ClassHubApp', '0007_remove_student_student_id'),
    ]

    operations = [
    ]
