# Generated by Django 4.2.19 on 2025-02-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0005_rename_creator_classroom_user_id'),
        ('ClassHubApp', '0008_merge_0004_attendence_0007_remove_student_student_id'),
    ]

    operations = [
    ]
