# Generated by Django 4.2.19 on 2025-02-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassHubApp', '0009_merge_20250222_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassHubApp.student'),
        ),
    ]
